# Form implementation generated from reading ui file '.\qtsrc\eyeplus\processDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialogProcessing(object):
    def setupUi(self, dialogProcessing):
        dialogProcessing.setObjectName("dialogProcessing")
        dialogProcessing.resize(375, 75)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            dialogProcessing.sizePolicy().hasHeightForWidth())
        dialogProcessing.setSizePolicy(sizePolicy)
        dialogProcessing.setMinimumSize(QtCore.QSize(300, 75))
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogProcessing)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelProcessing = QtWidgets.QLabel(dialogProcessing)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelProcessing.setFont(font)
        self.labelProcessing.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.labelProcessing.setObjectName("labelProcessing")
        self.verticalLayout.addWidget(self.labelProcessing)
        self.progressBarProcessing = QtWidgets.QProgressBar(dialogProcessing)
        self.progressBarProcessing.setProperty("value", 0)
        self.progressBarProcessing.setObjectName("progressBarProcessing")
        self.verticalLayout.addWidget(self.progressBarProcessing)

        self.retranslateUi(dialogProcessing)
        QtCore.QMetaObject.connectSlotsByName(dialogProcessing)

    def retranslateUi(self, dialogProcessing):
        _translate = QtCore.QCoreApplication.translate
        dialogProcessing.setWindowTitle(
            _translate("dialogProcessing", "eyeplus | Please Wait"))
        self.labelProcessing.setText(
            _translate("dialogProcessing", "Loading..."))
